### ISSUE TITLE
race: Error: EACCES: permission denied, mkdir './data/upload/'

### ISSUE THREAD

**Issue by ManucrackYT** [k3rnelpan1c-dev/uptime-kuma-helm#82]
![imagen](https://user-images.githubusercontent.com/71397795/211398882-86829cff-32e0-47d6-a080-8c0492fbd164.png)

**Comment by k3rnelpan1c-dev** [comment]
Hi there!
Thank you for the Issue, however I think I need a bit more info to whats going on here.

i.e.:

1. Which Container image are you using?
2. What is your container runtime and orchestrator?
3. which version of the chart and kuma we talking about?
4. ...

**Comment by ManucrackYT** [comment]
![imagen](https://user-images.githubusercontent.com/71397795/211665789-902df0ea-1bba-4ecd-aecd-826cda79c4a7.png)

Im trying to use latest kuma version from quay.io website, where you have it and trying to run it in a pterodacty server

**Comment by ManucrackYT** [comment]
Also, i dont have nothing in the "Startup script" of the Pterodacty egg, i mean, its empty

**Comment by k3rnelpan1c-dev** [comment]
> ![imagen](https://user-images.githubusercontent.com/71397795/211665789-902df0ea-1bba-4ecd-aecd-826cda79c4a7.png)
> 
> Im trying to use latest kuma version from quay.io website, where you have it and trying to run it in a pterodacty server

Hmmm, had not heard of _pterodacty server_ before this NGL.
Regardless, I assume it requires you to use a rootless container image, hence why you are here.

Just to be sure, you mounted a volume to `/app/data` within the container?
Because it looks like the kuma startup errors out due to a permission issue. So either there is no volume mounted or (if `pterodacty` uses bind mounts) the permissions are not set up right.

**Comment by pat-s** [comment]
Getting the same error on EKS 1.26.2 - fresh deployment

```
Welcome to Uptime Kuma
Your Node.js version: 16
2023-05-12T18:13:46Z [SERVER] INFO: Welcome to Uptime Kuma
2023-05-12T18:13:46Z [SERVER] INFO: Node Env: production
2023-05-12T18:13:46Z [SERVER] INFO: Importing Node libraries
2023-05-12T18:13:46Z [SERVER] INFO: Importing 3rd-party libraries
2023-05-12T18:13:49Z [SERVER] INFO: Creating express and socket.io instance
2023-05-12T18:13:49Z [SERVER] INFO: Server Type: HTTP
2023-05-12T18:13:49Z [SERVER] INFO: Importing this project modules
2023-05-12T18:13:49Z [NOTIFICATION] INFO: Prepare Notification Providers
2023-05-12T18:13:49Z [SERVER] INFO: Version: 1.21.3
Trace: Error: EACCES: permission denied, mkdir './data/upload/'
    at Object.mkdirSync (node:fs:1382:3)
    at Function.init (/app/server/database.js:104:16)
    at /app/server/server.js:172:14
    at Object.<anonymous> (/app/server/server.js:1565:3)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  errno: -13,
  syscall: 'mkdir',
  code: 'EACCES',
  path: './data/upload/'
}
    at process.<anonymous> (/app/server/server.js:1804:13)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2023-05-12T18:13:50Z [] INFO: Cannot write to error.log
Stream closed EOF for kuma/kuma-0 (uptime-kuma)
```


EDIT: using the "official" image works without issues

**Comment by k3rnelpan1c-dev** [comment]
Hmm, especially if the official image works fine, then this might be related to the environments where this happens relies on the entrypoint script fixing file permissions at boot.
However, this very script will not work in OpenShift due to it relying on the container running as the user `root` within itself, which you cannot do if you intent to use the default Security Context Constraint of OpenShift (`resrticted` or. `restricted-v2`).

This chart and image originated out of the need that I wanted to host Kuma on our OpenShift cluster without needing to escalate privileges nor allow another SCCs.
If I find a way and more importantly the time to evaluate why other container environments can run into this issue (not all seem to do so) then I will fix this, but unless someone beats me to it, while keeping `restricted-v2` SCC compatibility, I will recommend just overwriting the image tag in the chart to the official Kuma image.

**Comment by k3rnelpan1c-dev** [comment]
well, since there has been no real activity on this issue and that you can easily replace the image used in the chart with the official uptime-kuma image (in cases where you need the entrypoit script to fix permission) I will be closing this report in one weeks time.

Thank you for reporting this regardless and hope you have found a path to make it work for you in the end!

**Comment by pat-s** [comment]
Wouldn't it be more common to use the official image as the default in the chart and only add a pointer to the custom image? 

I guess if nothing has changed the issue is still present (didn't check for it lately though).

**Comment by k3rnelpan1c-dev** [comment]
> Wouldn't it be more common to use the official image as the default in the chart and only add a pointer to the custom image?
> 
> I guess if nothing has changed the issue is still present (didn't check for it lately though).

The issue may still persist, I have no environment to reproduce this behaviour though.

For your suggestion changing the default image, I could do that, but only with a major version bump as it is a breaking change to swap from a rootless image to a rootfull image.
Additionally, this helm chart and the rootless image originated from my need to deploy `uptime-kuma` on OpenShift without touching any SCCs (Security Context Constraints) and running in `Restricted`/`Restricted-v2` mode.

So, the only thing I can offer is either introduce the breaking change and screw over all (including myself) who expect to run a rootless image by default, or I include a second values file that default targets the "official" rootfull image.

I am all ears if you have any suggestion for alternative solutions.

**Comment by pat-s** [comment]
> For your suggestion changing the default image, I could do that, but only with a major version bump as it is a breaking change to swap from a rootless image to a rootfull image.
Additionally, this helm chart and the rootless image originated from my need to deploy uptime-kuma on OpenShift without touching any SCCs (Security Context Constraints) and running in Restricted/Restricted-v2 mode.

The question is (and only you can answer it) if this chart should be more a "general" chart for uptime-kuma (then I'd argue the image should be changed to upstream) or a personal/private chart of yours (then it should probably stay as is).

On "normal" k8s clusters the official image works fine and I think people should only be forced to a custom image by default if they are on a "custom" runtime 🙂 

If you'd do so, then yes, a major release would be the way to go to indicate the breaking change.

**Comment by epleterte** [comment]
You have to set securityContext options, and specifically `fsGroup` to get past this error.
Running the image rootless won't work if default permissions on the volume is "root ownership".

**Comment by k3rnelpan1c-dev** [comment]
I have thought about this a bit, and I may work on a v2 of the chart that will have an OpenShift flag in the values.
That way it should be as easy as to toggle that flag and recive either the upstream `rootfull` image or the `rootless` one. 
Alternatively, it could also just toggle the SecurityContext, but I prefer that to be an "advanced user" option, as most ppl don't bother to understand it.

Regardless, that would also be the point where I will try and switch the Chart packaging to target GH Pages as well as OCI (on Quay.io).

**Comment by k3rnelpan1c-dev** [comment]
*also sorry for the long silence, been busy with IRL responsibilities.

**Comment by illnr** [comment]
I had the same issue as OP in a plain k3s Cluster.
 
> You have to set securityContext options, and specifically `fsGroup` to get past this error. Running the image rootless won't work if default permissions on the volume is "root ownership".

Thanks epleterte! With your comment I could solve it like this:

```yaml
podSecurityContext:
          runAsNonRoot: true
          runAsUser: 3310
          runAsGroup: 3310
          fsGroup: 3310
          fsGroupChangePolicy: "OnRootMismatch"
```

**Comment by dkellenb** [comment]
Thanks @illnr for your suggestion. We had the same issue and with this it works as expected.

**Comment by taragurung** [comment]
I have the same issue when trying to enabling `persistence`
and setting parameters recommended above does not worked for me a well

**Comment by gecube** [comment]
I am expecting that the issue would be fixed on image level or on helm chart level.
Just enabled persistence on GKE and got this:

```bash
$ kubectl logs -n kuma uptime-kuma-0
Welcome to Uptime Kuma
Your Node.js version: 20.19.1
2025-09-14T12:15:45Z [SERVER] INFO: Welcome to Uptime Kuma
2025-09-14T12:15:45Z [SERVER] INFO: Node Env: production
2025-09-14T12:15:45Z [SERVER] INFO: Inside Container: false
2025-09-14T12:15:45Z [SERVER] INFO: Importing Node libraries
2025-09-14T12:15:45Z [SERVER] INFO: Importing 3rd-party libraries
2025-09-14T12:15:46Z [SERVER] INFO: Creating express and socket.io instance
2025-09-14T12:15:46Z [SERVER] INFO: Server Type: HTTP
2025-09-14T12:15:46Z [SERVER] INFO: Importing this project modules
2025-09-14T12:15:46Z [NOTIFICATION] INFO: Prepare Notification Providers
2025-09-14T12:15:46Z [SERVER] INFO: Version: 1.23.16
Trace: Error: EACCES: permission denied, mkdir 'data/upload/'
    at Object.mkdirSync (node:fs:1372:26)
    at Database.init (/app/server/database.js:114:16)
    at /app/server/server.js:184:14
    at Object.<anonymous> (/app/server/server.js:1664:3)
    at Module._compile (node:internal/modules/cjs/loader:1529:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1613:10)
    at Module.load (node:internal/modules/cjs/loader:1275:32)
    at Module._load (node:internal/modules/cjs/loader:1096:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: 'data/upload/'
}
    at process.unexpectedErrorHandler (/app/server/server.js:1905:13)
    at process.emit (node:events:524:28)
    at emitUnhandledRejection (node:internal/process/promises:250:13)
    at throwUnhandledRejectionsMode (node:internal/process/promises:385:19)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
If you keep encountering errors, please report to https://github.com/louislam/uptime-kuma/issues
2025-09-14T12:15:46Z [] INFO: Cannot write to error.log
```

the pod spec:

```bash
$ kubectl get pods -n kuma uptime-kuma-0 -oyaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-09-14T12:03:59Z"
  generateName: uptime-kuma-
  generation: 1
  labels:
    app.kubernetes.io/instance: uptime-kuma
    app.kubernetes.io/name: uptime-kuma
    apps.kubernetes.io/pod-index: "0"
    controller-revision-hash: uptime-kuma-67d5878ddb
    statefulset.kubernetes.io/pod-name: uptime-kuma-0
  name: uptime-kuma-0
  namespace: kuma
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: StatefulSet
    name: uptime-kuma
    uid: 205225d7-f7a0-4868-be35-8cb3bc4ab66d
  resourceVersion: "1757852153672111007"
  uid: 77d8fcc4-4fbb-4c17-a83f-6c46ff899677
spec:
  containers:
  - env:
    - name: UPTIME_KUMA_PORT
      value: "3001"
    - name: PORT
      value: "3001"
    image: quay.io/k3rnel-pan1c/uptime-kuma:1.23.16
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - extra/healthcheck
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: uptime-kuma
    ports:
    - containerPort: 3001
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /app/data
      name: uptime-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hmrt
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: uptime-kuma-0
  nodeName: gke-settings-default-pool-fb5d5e63-g6qj
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: uptime-kuma
  serviceAccountName: uptime-kuma
  subdomain: uptime-kuma
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: uptime-storage
    persistentVolumeClaim:
      claimName: uptime-kuma
  - name: kube-api-access-5hmrt
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-09-14T12:04:32Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-09-14T12:04:05Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-09-14T12:04:05Z"
    message: 'containers with unready status: [uptime-kuma]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-09-14T12:04:05Z"
    message: 'containers with unready status: [uptime-kuma]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-09-14T12:04:05Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://22bb4946a1b6e887f4375b3d0da9219c725ac34840b9cadfbd88c34cce701b15
    image: quay.io/k3rnel-pan1c/uptime-kuma:1.23.16
    imageID: quay.io/k3rnel-pan1c/uptime-kuma@sha256:600aefa19dd7ce16feb3cf5098a2efba68db1c49003de0b11564379b789a7878
    lastState:
      terminated:
        containerID: containerd://22bb4946a1b6e887f4375b3d0da9219c725ac34840b9cadfbd88c34cce701b15
        exitCode: 0
        finishedAt: "2025-09-14T12:15:46Z"
        reason: Completed
        startedAt: "2025-09-14T12:15:45Z"
    name: uptime-kuma
    ready: false
    resources: {}
    restartCount: 7
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=uptime-kuma pod=uptime-kuma-0_kuma(77d8fcc4-4fbb-4c17-a83f-6c46ff899677)
        reason: CrashLoopBackOff
    user:
      linux:
        gid: 3310
        supplementalGroups:
        - 3310
        uid: 3310
    volumeMounts:
    - mountPath: /app/data
      name: uptime-storage
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5hmrt
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.156.15.196
  hostIPs:
  - ip: 10.156.15.196
  phase: Running
  podIP: 10.60.3.27
  podIPs:
  - ip: 10.60.3.27
  qosClass: BestEffort
  startTime: "2025-09-14T12:04:05Z"
```

**Comment by gecube** [comment]
```yaml
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 3310
  runAsGroup: 3310
  fsGroup: 3310
  fsGroupChangePolicy: "OnRootMismatch"
```

worked for me, but only after the removal of old helm release and reinstalling it from scratch...

thanks to @illnr

**Comment by AurimasNav** [comment]
Same issue on AKS with persistence enabled.
